Import('env', 'common')

cereal_dir = Dir('.')
gen_dir = Dir('.')

# Build cereal
schema_files = ['car.capnp']
env.Command([f'{s}.c++' for s in schema_files] + [f'{s}.h' for s in schema_files],
            schema_files,
            f"capnpc --src-prefix={cereal_dir.path} $SOURCES -o c++:{gen_dir.path}/cpp/")

car_lib = env.Library('car', [f'{s}.c++' for s in schema_files])
